config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resource :user, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:index, :new, :create] do
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: [:edit, :update] do
    resources :comments, only: [:new, :create]
  end
end

app/views/shared/_csrf.html.erb
<input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

app/views/shared/_edit_delete.html.erb
<% if current_user == post.author %>
  <%= button_to "Edit", edit_post_url(post), method: :get %>
  <%= button_to "Delete", post_url(post), method: :delete %>
<% end %>

app/views/shared/_login.html.erb
<form action="<%= new_user ? user_url : session_url %>" method="post">
  <%= render "shared/csrf" %>
  <div class="my form-group">
    <label>Username:
      <input class="form-control" type="text" name="user[username]" value="<%= user.username %>">
    </label>
    <br>
    <% if new_user %>
      <br>
      <label>Email:
        <input class="form-control" type="text" name="user[email]" value="<%= user.email %>">
        <br>
      </label>
    <% end %>
    <br>
    <label>Password
      <input class="form-control" type="password" name="user[password]">
    </label>
    <br>
    <br>

    <input class="btn btn-default" type="submit" name="Submit">
  </div>
</form>

app/views/shared/_patching.html.erb
<input type="hidden" name="_method" value="patch">