config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resource :user, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:index, :new, :create] do
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: [:edit, :update] do
    resources :comments, only: [:new, :create]
  end
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  moderator_id :integer          not null
#  name         :string           not null
#  description  :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates_presence_of :moderator_id, :name
  validates_uniqueness_of :name

  belongs_to(
    :moderator,
    class_name: :User,
    foreign_key: :moderator_id,
    primary_key: :id,
    inverse_of: :subs
  )

  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs, inverse_of: :subs
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  include Findable

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = current_user.subs.new(sub_params)

    if @sub.save
      flash[:messages] = ["Sub created successfully"]
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      @sub = Sub.new
      render :new
    end
  end

  def edit
    if current_user != @sub.moderator
      flash[:errors] = ["Can't edit THAT sub!"]
      redirect_to subs_url
    end
  end

  def update
    if @sub.update(sub_params)
      flash[:messages] = ["Sub edited successfully"]
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      @sub = Sub.find(params[:id])
      render :edit
    end
  end

  def show
  end

  private

  def sub_params
    params.require(:sub).permit(:moderator_id, :name, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<form class="create" action="<%= creating ? subs_url : sub_url(sub) %>" method="post">
  <%= render 'shared/csrf' %>
  <%= render 'shared/patching' unless creating %>

  <label>Name:
    <input type="text" name="sub[name]" value="<%= sub.name %>">
  </label>
  <br>

  <label>Description:
    <textarea name="sub[description]" rows="8" cols="40"
      placeholder="Describe sub here"><%= sub.description %></textarea>
  </label>

  <input type="submit" name="Submit">
</form>

app/views/subs/edit.html.erb
<h1>Edit this sub!</h1>
<hr>
<%= render 'form', creating: false, sub: @sub %>

app/views/subs/index.html.erb
<h1>Sub Redditerests:</h1>
<hr>
<%= link_to "Create new sub", new_sub_url %>
<br>
<% firstcol = @subs[0...@subs.length/2] %>
<% secondcol = @subs[@subs.length/2...@subs.length] %>
<div class="row">
  <div class="col-md-6">
    <% firstcol.each do |sub| %>
      <a href="<%= sub_url(sub) %>" class="sub">
        <h4> <%= sub.name %> </h4>
      </a>
    <% end %>
  </div>
  <div class="col-md-6">
    <% secondcol.each do |sub| %>
      <a href="<%= sub_url(sub) %>" class="sub">
        <h4> <%= sub.name %> </h4>
      </a>
    <% end %>
  </div>

</div>

app/views/subs/new.html.erb
<h1>Create a new sub!</h1>
<hr>
<%= render 'form', creating: true, sub: @sub %>

app/views/subs/show.html.erb
<%= button_to "List of Subs", subs_url, method: :get %>
<h1><%= @sub.name %></h1>
<h3><%= @sub.description %></h3>
<hr>
<%= button_to "Create new post", new_sub_post_url(@sub), method: :get %>


<div class="media">
  <% @sub.posts.each do |post| %>
    <div class="post media-left">
      <%= link_to post.title, post_url(post) %>
      <%= render 'shared/edit_delete', post: post %>
    </div>
  <% end %>
</div>