config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resource :user, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:index, :new, :create] do
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: [:edit, :update] do
    resources :comments, only: [:new, :create]
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  author_id  :integer          not null
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates_presence_of :title, :author_id, :subs

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs, inverse_of: :posts

  belongs_to(
    :author,
    foreign_key: :author_id,
    class_name: :User,
    inverse_of: :posts
  )

  has_many :comments, inverse_of: :post, dependent: :destroy

  def comments_by_parent_id
    @cpid = Hash.new { |h,k| h[k] = [] }
    comments.each do |comment|
      @cpid[comment.parent_id] << comment
    end
    @cpid
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Findable

  def new
    # @sub = Sub.find(params[:sub_id])
    # @post = @sub.posts.new
    @post = Post.new
    @post.subs << Sub.find(params[:sub_id])
    # fail
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:messages] = ["Post created successfully"]
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      @post = Post.new
      @post.subs << Sub.find(params[:sub_id])
      render :new
    end
  end

  def show
  end

  def edit
    if @post.author != current_user
      flash[:errors] = ["You can't edit that post"]
      redirect_to sub_url(@post.subs.first)
    end
  end

  def update
    if @post.update(post_params)
      flash[:message] = ["Post updated successfully"]
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :sub_ids => [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<form class="post" action="<%= creating ? sub_posts_url : post_url(post) %>" method="post">
  <%= render "shared/patching" unless creating %>
  <%= render "shared/csrf" %>

  <label>Title:
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <br>

  <label>Body:
    <textarea name="post[content]"
      placeholder="Type the body of your post here"><%= post.content %></textarea>
  </label>

  Subs:
  <% Sub.all.each do |sub| %>
    <label>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"
        <%= "checked" if post.subs.include?(sub) %> >
      <%= sub.name %>
    </label>
  <% end %>

  <input type="submit" name="Submit">
</form>

app/views/posts/_nested_comment.html.erb
<div class="comment" id="<%=comment.id%>" style="margin-left:<%= 30 + level * 30 %>px">
  <div class="content"><%= comment.content %></div>

  <button onClick=addComment(<%= comment.id %>)> Add Comment </button>
  <% if comment.author = current_user %>
    <button onClick=editComment(<%= comment.id %>)> Edit Comment </button>
  <% end %>
</div>
<hr>
<% post.comments_by_parent_id[comment.id].each do |child_comment| %>
  <%= render 'nested_comment', comment: child_comment, post: post, level: level + 1 %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<h3>in: <%= @post.subs.map { |sub| sub.name }.join(", ") %> </h3>
<hr>
<%= render 'form', creating: false, post: @post %>

app/views/posts/new.html.erb
<h1><%= @post.subs.first.name %> - New Post</h1>
<hr>
<%= render 'form', creating: true, post: @post %>

app/views/posts/show.html.erb
<script>
  function addComment(id) {
    var selector = id ? ".comment#" + id : ".post"
    $(selector).append(
      $("div.comment_form").show()
    )
    $("form.comment_form").attr("action", function () {
      return id ? "<%= root_url %>comments/" + id + "/comments" : "<%= post_comments_url(@post) %>"
    })
  }

  function editComment(id) {
    var selector = ".comment#" + id
    var comment = $(selector + " .content").text()
    console.log(comment)
    $(".comment:hidden").show()
    $(selector)
      .hide()
      .after(
        $("div.comment_form").show()
      )
    $("form.comment_form ")
      .attr("action", function () {
        return "<%= root_url %>/comments/" + id
      })
      .append("<input type='hidden' name='_method' value='patch'>")
    $("textarea.comment_form").val(comment)
  }
</script>


<h1><%= @post.title %> </h1>
<h3>in: <%= @post.subs.map { |sub| link_to(sub.name, sub_url(sub)) }.join(", ").html_safe %> </h3>
<br>
<%= render 'shared/edit_delete', post: @post %>
<hr>
<div class="post">
  <%= @post.content %>
</div>
<hr>

<button onClick=addComment()> Add Comment </button>

<% @post.comments_by_parent_id[nil].each do |comment| %>
  <%= render 'nested_comment', comment: comment, post: @post, level: 1, action: @action %>
<% end %>

<div class="comment_form", style="display:none;">
  <form class="comment_form" method='post'>
    <%= render 'shared/csrf' %>
    <textarea class="comment_form" cols='100' rows='8' class='newcomment' name='comment[content]' value=''></textarea>
    <input type='submit' name='Submit'>
  </form>
</div>