config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resource :user, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:index, :new, :create] do
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: [:edit, :update] do
    resources :comments, only: [:new, :create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redditerest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container main">
  <nav class="navbar navbar-inverse">
    <div class="header">

      <ul class="nav navbar-nav">
        <li class="navbar-text" > <a class="h2 active" href="#"> Redditerest </a></li>
        <li class=" navbar-text"> <a class="h2" href="<%= subs_url %>">Sub Redditerests</a> </li>
      </ul>
      <ul class="nav navbar-right nav-pills">
        <% if current_user  %>
          <li class="active navbar-text"><%= link_to "Log Out", session_url, class: "h5", method: :delete %></li>
        <% else %>
          <li class="active navbar-text"><%= link_to "Log In", new_session_url, class: "h5" %></li>
          <li class="active navbar-text"><%= link_to "Sign Up", new_user_url, class: "h5" %></li>
        <% end %>
      </ul>
    </div>
  </nav>


  <% flash.each do |name, msgs| %>
    <% msgs.each do |msg| %>
      <%= content_tag(:div, msg, class: name + " jumbotron flash_message") %>
    <% end %>
  <% end  %>



  <div class="container">
    <%= yield %>

  </div>
</div>


</body>
</html>